### ISSUE TITLE
What libraries are you linking against?

### ISSUE THREAD

**Issue by bsenftner** [dolmens/wxFFmpeg#1]
I tried a git clone of this project using a git bash window on Win10. Following the build instructions in the README.md, the first cmake line errors trying to locate my wxWidgets install. Using the CMake GUI, I was unable to satisfy the config requirements. Rather than play trial and error, I simply created a Visual Studio Community 2019 project and manually set the various include and library directories.

I am linking against the dependencies included via the "git submodule update --init" in step one of your build instructions.
I am also linking (statically) against wxWigets 3.1.3 and ffmpeg 4.4.

I am currently down to one unresolved external symbol:
  unresolved external symbol IID_ICodecAPI referenced in function mf_init	wxFFmpeg	C:\dev\cpp20\wxFFmpeg\libavcodec.a(mfenc.o)

I have another ffmpeg wxWidgets project, one I authored from scratch, which I've copied the various link libraries over to this project. But I still have that one unresolved symbol. I am not sure if I need all these, but here's what I am currently linking against:

comctl32.lib
common.lib
ex-common.lib         <- do I need both common.lib and ex-common.lib? 
wxmsw31ud_gl.lib
wxmsw31ud_core.lib
wxbase31ud.lib
wxtiffd.lib
wxjpegd.lib
wxpngd.lib
wxzlibd.lib
wxregexud.lib
wxexpatd.lib
libavcodec.a
libavdevice.a
libavfilter.a
libavformat.a
libavutil.a
libswresample.a
libswscale.a
libpostproc.a
libx264.lib
bcrypt.lib
crypt32.lib
Rpcrt4.lib
opengl32.lib
glu32.lib
glew32.lib
Vfw32.lib
OpenAL32.lib
Secur32.lib
Ws2_32.lib
Mfplat.lib
Mfuuid.lib
LIBCMTD.lib
MSVCRTD.lib

If interested, my ffmpeg converts the YUV to RGB and I noticed you do not, you're using the YUV directly in a shader, and that is interesting to me.

**Comment by dolmens** [comment]
May be `strmiids.lib`, `mfplat.lib` and `mfuuid.lib`. Not tested.

**Comment by bsenftner** [comment]
I was missing strmiids.lib in my version. Thank you. Checking the runtime and so on out now... Nice work.
