### ISSUE TITLE
curious about your coding style

### ISSUE THREAD

**Issue by bsenftner** [dolmens/wxFFmpeg#2]
dolmens,
I am curious where you learned ffmpeg's internals. Your implementation is very clean and minimal. I have looked under the hood of a few ffmpeg players and other applications incorporating ffmpeg libraries and the code is no where as clean as what I see you've written. So, back to my initial question: where did you learn ffmpeg's library usage?

**Comment by dolmens** [comment]
Aha. Just ffplay from FFmpeg project and samples from OpenAL-soft project.

**Comment by bsenftner** [comment]
Huh. I based my player library on ffplay as well, but it has more lines of code. I started with ffplay around '15 and have been updating it with each release. It's targeted at embedding in a machine learning / video analyzing framework, so it supports files, USB and IP video, analytics/operations callbacks, RGB frames, and frame scrubbing. But your code is 1/8th the size, so I'm impressed.
